name: Ui Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - vue3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Run Lint
      run: npm run lint
    - name: Run Unit Tests
      run: npm run test
